
export const ADD_CHIP = 'ADD_CHIP';
export const REMOVE_CHIP = 'REMOVE_CHIP';
export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
//export const LOCATION_REQUEST = 'LOCATION_REQUEST';
export const LOCATION_SET_POSITION = 'LOCATION_SET_POSITION';
export const LOCATION_SET_ERROR = 'LOCATION_SET_ERROR';
